//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyDatabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public Cliente()
        {
            this.Contas = new HashSet<Conta>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<Conta> Contas { get; set; }
    }
}
