//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyDatabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conta
    {
        public int id { get; set; }
        public decimal saldo { get; set; }
        public int cliente { get; set; }
    
        public virtual Cliente Cliente1 { get; set; }
    }
}
