//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace exercicio3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Afecto
    {
        public int areaInt { get; set; }
        public int numFunc { get; set; }
        public System.DateTime dataHabilArea { get; set; }
        public bool éCoordenador { get; set; }
    
        public virtual AreaIntervencao AreaIntervencao { get; set; }
        public virtual Funcionario Funcionario { get; set; }
    }
}
