//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace exercicio3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Funcionario
    {
        public Funcionario()
        {
            this.Afectoes = new HashSet<Afecto>();
            this.Trabalhoes = new HashSet<Trabalho>();
        }
    
        public int num { get; set; }
        public string nome { get; set; }
        public System.DateTime dataNasc { get; set; }
    
        public virtual ICollection<Afecto> Afectoes { get; set; }
        public virtual ICollection<Trabalho> Trabalhoes { get; set; }
    }
}
