//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace exercicio3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sector
    {
        public Sector()
        {
            this.Ocorrencias = new HashSet<Ocorrencia>();
        }
    
        public int codInst { get; set; }
        public int piso { get; set; }
        public string zona { get; set; }
        public string descrição { get; set; }
        public bool extintor { get; set; }
    
        public virtual Instalacao Instalacao { get; set; }
        public virtual ICollection<Ocorrencia> Ocorrencias { get; set; }
    }
}
