//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace exercicio3
{
    using System;
    using System.Collections.Generic;
    
    public partial class TotalOcorrenciaPorEmpresaPorTipo
    {
        public int empresa { get; set; }
        public string tipo { get; set; }
        public Nullable<int> nrOcorrTipo { get; set; }
    }
}
